### ISSUE TITLE
cec-client cannot open connection on RPI

### ISSUE THREAD

**Issue by spectrokid** [Pulse-Eight/libcec#191] opened 2016-02-03 19:22 UTC
On raspberry II , I followed the compile instructions (fresh raspbian copy) and didn't get any error messages during compile/make.
 Version:

```
 pi@raspberrypi:~ $ sudo cec-client -i
    libCEC version: 3.1.0, git revision: libcec-3.1.0+5-6d68d21, compiled on Wed  3 Feb 18:53:24 UTC 2016 by pi@raspberrypi on Linux 4.1.13-v7+ (armv7l), features: P8_USB, DRM, P8_detect, randr, RPi
```

**_result_**

```
pi@raspberrypi:~ $ sudo cec-client -m
starting a monitor-only client. use 'mon 0' to switch to normal mode
No device type given. Using 'recording device'
CEC Parser created - libCEC version 3.1.0
no serial port given. trying autodetect:
 path:     Raspberry Pi
 com port: RPI

opening a connection to the CEC adapter...
DEBUG:   [              68]     Broadcast (F): osd name set to 'Broadcast'
DEBUG:   [              68]     InitHostCEC - vchiq_initialise succeeded
DEBUG:   [              68]     InitHostCEC - vchi_initialise succeeded
DEBUG:   [              68]     InitHostCEC - vchi_connect succeeded
ERROR:   [              69]     RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
ERROR:   [              69]     Open - vc_cec could not be initialised
ERROR:   [              69]     could not open a connection (try 1)

```

**Comment by opdenkamp** [comment] 2016-02-25 17:20
the firmware is rejecting `vc_cec_set_logical_address(E)` for some reason. perhaps @popcornmix has an idea why? haven't seen that happening for address E before

**Comment by dsebastien** [comment] 2016-04-24 05:51
Same issue for me (...address(E) also shows up in my logs: #186

**Comment by voltagex** [comment] 2016-09-07 13:37
Ping, just hit this same issue. 

```
voltagex@kiwi:/opt/vc/bin$ cec-client -i
libCEC version: 3.1.0, compiled on Linux-4.1.17-v7+ ... , features: P8_USB, DRM, P8_detect, randr, RPi
```

**Comment by voltagex** [comment] 2016-09-07 13:58
Upgraded to 4.4.19-v7+ and it worked. I'm going to guess that the libraries/headers I built against were "too new" for the rest of the system.

**Comment by pantomico** [comment] 2016-09-10 13:32
Nope:```
 sudo cec-client -i
`libCEC version: 3.1.0, git revision: libcec-3.1.0+25-62b8520, compiled on Sat 10 Sep 13:21:22 UTC 2016 by pi@raspberrypi on **Linux 4.4.20-v7**+ (armv7l), features: P8_USB, DRM, P8_detect, randr, RPi`

Still getting same error:
`ERROR:   [            9060]     RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
`
```

**Comment by pantomico** [comment] 2016-09-12 11:29
@voltagex : would you be willing to dropbox me a complete drive image of your Raspberry?  This issue has been bugging me for 6 months now...

**Comment by viruzofficial** [comment] 2016-10-08 10:49
I'm also running in the same issue ... 

libCEC version: 3.1.0, git revision: libcec-3.1.0+25-62b8520, compiled on Sat  8 Oct 10:25:51 UTC 2016 by pi@raspberrypi on Linux 4.4.13-v7+ (armv7l), features: P8_USB, DRM, P8_detect, randr, RPi

Can anyone help?

**Comment by voltagex** [comment] 2016-10-08 23:26
Yeah, what does cec-client -s say?

**Comment by viruzofficial** [comment] 2016-10-10 15:39
`cec-client -s
opening a connection to the CEC adapter...
DEBUG:   [              81]     Broadcast (F): osd name set to 'Broadcast'
DEBUG:   [              82]     InitHostCEC - vchiq_initialise succeeded
DEBUG:   [              82]     InitHostCEC - vchi_initialise succeeded
DEBUG:   [              82]     InitHostCEC - vchi_connect succeeded
ERROR:   [              83]     RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
ERROR:   [              83]     Open - vc_cec could not be initialised
ERROR:   [              83]     could not open a connection (try 1)
DEBUG:   [            1084]     InitHostCEC - vchiq_initialise succeeded
DEBUG:   [            1084]     InitHostCEC - vchi_initialise succeeded
DEBUG:   [            1084]     InitHostCEC - vchi_connect succeeded
ERROR:   [            1085]     RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
ERROR:   [            1085]     Open - vc_cec could not be initialised
ERROR:   [            1085]     could not open a connection (try 2)`

Don't know if this is helpful:(

**Comment by pantomico** [comment] 2016-10-10 17:01
yup, same here:

```
pi@raspberrypi:~ $ cec-client -s
opening a connection to the CEC adapter...
DEBUG:   [              79]     Broadcast (F): osd name set to 'Broadcast'
DEBUG:   [              79]     InitHostCEC - vchiq_initialise succeeded
DEBUG:   [              79]     InitHostCEC - vchi_initialise succeeded
DEBUG:   [              79]     InitHostCEC - vchi_connect succeeded
ERROR:   [              80]     RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
ERROR:   [              80]     Open - vc_cec could not be initialised
ERROR:   [              80]     could not open a connection (try 1)
DEBUG:   [            1081]     InitHostCEC - vchiq_initialise succeeded
DEBUG:   [            1081]     InitHostCEC - vchi_initialise succeeded
DEBUG:   [            1081]     InitHostCEC - vchi_connect succeeded
ERROR:   [            1081]     RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
```

**Comment by petonic** [comment] 2016-10-14 18:07
Same here....  Same output as pantomicio.

My output of `cec-client -i` is: 

    pi@pithy:/opt/vc/bin$ cec-client -i
    libCEC version: 3.1.0, git revision: libcec-3.1.0+25-62b8520, compiled on Fri Oct 14 17:58:22 UTC 2016 by pi@pithy on Linux 4.4.21-v7+ (armv7l), features: P8_USB, DRM, P8_detect, randr, RPi
    pi@pithy:/opt/vc/bin$

**Comment by voltagex** [comment] 2016-10-15 05:48
I suspect you all need to do a kernel+firmware upgrade.

**Comment by pantomico** [comment] 2016-10-15 07:27
Nope, this was right after an rpi-update followed by an apt-get upgrade.

**Comment by opdenkamp** [comment] 2016-10-18 13:27
I cannot reproduce this when downloading the latest Raspbian Jessie from https://www.raspberrypi.org/downloads/raspbian/ and following the instructions from https://github.com/Pulse-Eight/libcec/blob/master/README.md to the letter.

**Comment by opdenkamp** [comment] 2016-10-18 13:29
Perhaps you're trying to use cec-client while another program (Kodi?) is using it, which won't work. As this doesn't happen when using a clean installation and following the instructions, I'm closing this issue.

**Comment by opdenkamp** [comment] 2016-10-18 15:18
Right, let's re-open this one. Can one of you who's having this issue try to compile it with commit https://github.com/Pulse-Eight/libcec/commit/9ddb93b91a9e5dc7d89cccd6c593c64cf57a6d92 reverted and report back.

**Comment by opdenkamp** [comment] 2016-10-18 17:36
@MilhouseVH was kind enough to do an openelec build without 9ddb93b in: http://milhouse.libreelec.tv/builds/testing/RPi2/LibreELEC-RPi2.arm-8.0-Milhouse-20161018174530-%231018y-gdc3b078.tar

**Comment by MilhouseVH** [comment] 2016-10-18 17:40
LibreELEC, but close enough... :smile:

**Comment by pantomico** [comment] 2016-10-18 19:08
I'm a complete newby at Git, so I don't know how to do this automatically.  I went through the source and removed the offending lines by hand.  I (believe it or not) got it to compile, but when I ran the client, I got precisely the same eror message as before.

**Comment by pantomico** [comment] 2016-10-20 17:27
Ok, the plot is thickening.  I had to buy a new memory card so I bought one with Raspbian preinstalled.  From a fresh install, I got it to work.  One thing I thought about is that I configured it to start a graphical desktop, where I previously was set up to start in CLI.  Could this make the difference?

I did get these compilation warnings:
`[ 21%] Building CXX object src/libcec/CMakeFiles/cec.dir/adapter/AdapterFactory.cpp.o
In file included from /home/pi/libcec/src/libcec/adapter/RPi/RPiCECAdapterCommunication.cpp:37:0:
/home/pi/libcec/src/libcec/adapter/RPi/RPiCECAdapterCommunication.h: In constructor ‘CEC::CRPiCECAdapterCommunication::CRPiCECAdapterCommunication(CEC::IAdapterCommunicationCallback*)’:
/home/pi/libcec/src/libcec/adapter/RPi/RPiCECAdapterCommunication.h:118:35: warning: ‘CEC::CRPiCECAdapterCommunication::m_bDisableCallbacks’ will be initialized after [-Wreorder]
     bool                          m_bDisableCallbacks;
                                   ^
/home/pi/libcec/src/libcec/adapter/RPi/RPiCECAdapterCommunication.h:105:10: warning:   ‘bool CEC::CRPiCECAdapterCommunication::m_bInitialised’ [-Wreorder]
     bool m_bInitialised;   /**< true when the connection is initialised, false otherwise */
          ^
/home/pi/libcec/src/libcec/adapter/RPi/RPiCECAdapterCommunication.cpp:68:1: warning:   when initialized here [-Wreorder]
 CRPiCECAdapterCommunication::CRPiCECAdapterCommunication(IAdapterCommunicationCallback *callback) :
 ^
[ 24%] Building CXX object src/libcec/CMakeFiles/cec.dir/adapter/Pulse-Eight/USBCECAdapterMessage.cpp.o
`

**Comment by 21bob21** [comment] 2016-12-26 22:38
hi

**Comment by inphinitum** [comment] 2017-01-03 21:12
I'm having the same issue here. Vanilla Raspbian cli version, libcec compiled from master.

**Comment by chrisbward** [comment] 2017-01-04 13:54
Having the same issue on Jessie on a Pi B model;
libCEC version: 4.0.1, git revision: libcec-4.0.1, compiled on Wed  4 Jan 12:49:31 UTC 2017 by pi@raspberrypi-tv on Linux 4.4.38+ (armv6l), features: P8_USB, DRM, P8_detect, randr, RPi

**Comment by inphinitum** [comment] 2017-01-04 14:05
@chrisbward have you tried to force HDMI output via `raspi-config`? I did so and the problem went away.

**Comment by chrisbward** [comment] 2017-01-04 14:15
also done that - this is from a blank Jessie install, however my kernel was at 4.1.x before - tried an rpi-update and then make install on-top of the original 
- will I need to clear the system out before I build again?

**Comment by opdenkamp** [comment] 2017-01-04 14:33
I tried this with a clean installation, on a blank SD card, a while ago and couldn't reproduce it.

The symptoms suggest that the kernel checks for HPD of the connected sink and will return an error if it doesn't detect this. I've seen other hardware that does similar things, but when I spoke to the engineer who works on the Pi's firmware yesterday, he told me that he didn't think that it was the case for the Pi, but wasn't sure. He said that he'll take a look at it once he's back from travelling.

It's not a problem with libCEC or something that libCEC can address. Just keeping this ticket open for now, until I've heard back about the firmware.

**Comment by chrisbward** [comment] 2017-01-04 15:09
I will wipe the SD and follow the instructions again;
https://github.com/Pulse-Eight/libcec/blob/master/docs/README.raspberrypi.md

**Comment by chrisbward** [comment] 2017-01-04 19:35
okay... seems to be working now...!

biggest differences in this instance;
- avoided running apt-get install cec-utils
- installed and ran rpi-update from 4.4.34 to 4.4.38 (raspbian jessie lite - 25th nov 16)
- turned on audio for HDMI in raspi-config
- followed instructions in link in above comment

thanks guys, will start testing now

**Comment by sterling** [comment] 2017-01-13 19:52
I was able to fix this problem for myself by doing: `tvservice --off`. This will power down the HDMI and open it up for connections again if something you can't identify has taken over.

**Comment by jsan55** [comment] 2017-02-13 08:21
Thanks sterilng,
 "**tvservice - off**" was also my solution. I have summarized the most important here.
Control your LG Smart TV with Linux 
[http://www.pedaltreter.at/jsan/lgtv/LG_Smart_TV_CEC_en.html](url)

**Comment by opdenkamp** [comment] 2017-03-15 09:35
I've added a warning in libCEC, when it detects this. Thanks

**Closed by opdenkamp** 2017-03-15 09:35 UTC
