### ISSUE TITLE
Compatibility Windows 10 Universal (Windows 10 Iot Core)

### ISSUE THREAD

**Issue by marnixcox** [Pulse-Eight/libcec#130] opened 2015-08-20 11:36 UTC
SetupDiGetClassDevs is only supported on Windows 10 Desktop. 

For Windows 10 Universal (Windows 10 Iot Core -> Raspberry Pi) CM_Get_Device_ID_List / CM_Get_Device_Interface_List needs to be used.

https://msdn.microsoft.com/zh-tw/library/windows/hardware/ff551069(v=vs.85).aspx

**Comment by opdenkamp** [comment] 2015-11-26 13:49
oh lovely, it looks like the two may not be compatible with each other.

```
SetupDiGetClassDevs function
Target platform: Desktop
For universal, call CM_Get_Device_ID_List
For universal, call CM_Get_Device_Interface_List
```

```
CM_Get_Device_Interface_List function
Remarks: Use SetupDiGetClassDevs instead of CM_Get_Device_Interface_List
Target platform: Universal
```

**Comment by opdenkamp** [comment] 2015-11-27 15:56
luckily they are compatible, but I haven't found out how to read the registry key with the com port yet with one of the CM_* methods

**Comment by opdenkamp** [comment] 2015-12-01 09:31
this is going to be something for the next major update

**Comment by davidGoff** [comment] 2016-01-26 10:06
Hello, 
I'm a bit lost with these comments about windows iot.
Is there a work around to use libcec on this os? if not do you know if it is planned in a near future? 

I'm a C# dev with no specific knowledge in CEC, but I'll be glad to help you if there is something to test/ adapt. 

Best regards, 
David

**Comment by opdenkamp** [comment] 2016-01-26 10:43
I've replaced a couple of the winapi calls by the iot core compatible ones, but I couldn't find a method to read the registry entry that contains the com port that the system allocated for the device that's compatible with iot core when I looked at it earlier. That's in the C++ part: https://github.com/Pulse-Eight/libcec/blob/master/src/libcec/adapter/Pulse-Eight/USBCECAdapterDetection.cpp

I'll look into it before the next major update, but I can't give an ETA on that one at this time.

**Comment by AndreaSpan** [comment] 2016-08-22 07:28
Hi,

Anything new about using libcec on Windows 10 Universal (Windows 10 Iot Core)? 

Thank you!

**Comment by DaveVoyles** [comment] 2016-10-05 17:59
Following along, because I'd love to get this working on Win 10 IoT as well.

**Comment by naice** [comment] 2016-10-20 05:35
Also following. My MagicMirror is in Heavy need of switching On/Off its display. 

https://www.hackster.io/Emmuss/magicmirror-cb222b

**Comment by gerritsen** [comment] 2017-03-20 09:46
Any news on this? Waiting a long time on it. Hope it will be fixed soon!

**Comment by jacobp85** [comment] 2017-03-28 19:55
Any ETA?

**Comment by opdenkamp** [comment] 2017-07-13 10:24
Sorry, we haven't had time for this yet. It's a not a bug, but more like supporting a new operating system in this case.

**Comment by opdenkamp** [comment] 2020-04-27 10:26
.net core / uwp is now supported in master. it will be included in the next release.
we only provide installers for x86/x64 on Windows. I haven't looked at cross compiling for ARM yet

**Closed by opdenkamp** 2020-04-27 10:26 UTC
Labels: enhancement, future
