### ISSUE TITLE
Sony KDL55W829BBU not seeing RPi3 as CEC Device

### ISSUE THREAD

**Issue by DaveTBlake** [Pulse-Eight/libcec#252] opened 2016-10-17 13:20 UTC
Unfortunately I'm still having problems with CEC from Sony TV (KDL55W829BBU), as initially discussed in #126 last year. Same TV but I now have a new pi. I had given up on CEC, yet randomly after a power cycle a few nights ago I briefly had CEC working! TV out of standby next day, and CEC was gone again, but this gives me hope that CEC could work, and so worth pursuing.

I have tried power cycling again, all kinds of combinations, and no CEC. I have to wonder if there is some timing issue between devices?

Details: Librelec 7.90.005 on RPi3 (hence libcec 3.1.0)
Log file here http://pastebin.com/uzike67h
Getting error:
"CecLogMessage - RegisterLogicalAddress - vc_cec_set_logical_address(1) returned device is busy (3)"

@opdenkamp could you take a look at this please.

As before have tried:
Connecting to a different HDMI port makes no difference.
New CEC enabled cable makes no difference.
Power cycling makes no difference, neither does trying different HDMI ports.
RPi as only HDMI devive makes no difference, no devices shown in list.
The TV does detect the presence of other possible CEC devices e.g. when a PVR is plugged in.
Second Pi to have this issue see

**Comment by DaveTBlake** [comment] 2016-10-18 13:10
Have upgraded to LE 7.90.007
Immediately after upgrade CEC worked (TV was on during install), but next day after TV had been in standby and RPi left on it stopped. Tried power cycling devices again in various combinations, but it didn't help.
Log file here 
http://pastebin.com/S0viWiKy

Installed a Millhouse build (#1015) that is +15 posts on libcec 3.1.0, but could not get CEC to work no matter the power-up combination I tried, and installing didn't make it work this time either.

A timing issue of some kind?

**Comment by opdenkamp** [comment] 2016-10-18 14:48
This is a duplicate of https://github.com/Pulse-Eight/libcec/issues/191 which I cannot reproduce when using current master with the current version of Raspian.

Something must have changed in the Pi's firmware that causes this as nothing has changed in libCEC afaict that could cause this since the first version that supported the Pi

**Comment by popcornmix** [comment] 2016-10-18 14:58
Last change to firmware CEC code was July 2014. I can't imagine a firmware change causing this issue.

**Comment by opdenkamp** [comment] 2016-10-18 15:05
This is the only code change that I can imagine that could be causing this: https://github.com/Pulse-Eight/libcec/commit/9ddb93b91a9e5dc7d89cccd6c593c64cf57a6d92

It got introduced in May 2015, but didn't get included in a release before 3.1.0.

But I can't reproduce any issues like this, tested on multiple TVs and with multiple devices connected, using a fresh Raspbian installation that I downloaded and apt-get upgraded this morning

**Comment by popcornmix** [comment] 2016-10-18 15:14
I don't believe @DaveTBlake 's TV has ever worked with libCEC.
He [reported problems](http://forum.kodi.tv/showthread.php?tid=232332) with OpenELEC 5.95.2 (over a year old) which I suspect wouldn't have had that commit.

**Comment by opdenkamp** [comment] 2016-10-18 15:21
Could you try to revert commit https://github.com/Pulse-Eight/libcec/commit/9ddb93b91a9e5dc7d89cccd6c593c64cf57a6d92 and upload a new log without that commit in @DaveTBlake

**Comment by DaveTBlake** [comment] 2016-10-18 15:27
I can confirm that my TV has did not work with libCEC and OpenElec 5.95.2. Having tried all the hardware changes I could never prove it was not the RPi itself because I didn't have any other TV to test it with so I gve up.

With LibreElec on a new RPi3 the CEC randomly worked for an evening - the first time of CEC and Kodi, although other devices were OK with CEC on the TV.  Hence I have become hopeful that a solution can be found.

Sorry @opdenkamp not sure how to build own LE  version to test the reversion of that commit. I dev Kodi on Windows, but a bit lost on other platforms. If you can guide me more then I am happy to try and work through this.

 it is just over a year old so not an old set. OpenElec

**Comment by opdenkamp** [comment] 2016-10-18 15:32
Hm right, you can't replace libcec.so easily on openelec because of the read only filesystem.
I can build the lib for you, and you could stick it in /tmp and use LD_LIBRARY_PATH to point to it when starting Kodi, but I'm not sure how to stop the running Kodi on OpenElec and run your own.

Is a Kodi build available for Raspbian? Then it's easy to do if you have a spare SD card.

**Comment by popcornmix** [comment] 2016-10-18 15:35
Ping @MilhouseVH - could you revert this commit in tonight's build LibreELEC build?
(assuming there aren't conflicts from later commits)

**Comment by MilhouseVH** [comment] 2016-10-18 16:29
I'm not able to revert https://github.com/Pulse-Eight/libcec/commit/9ddb93b91a9e5dc7d89cccd6c593c64cf57a6d92 cleanly, but I've reverted the changes with https://gist.github.com/MilhouseVH/530f703f13b762f73422e0209345c4b2 instead.

Rather than include this in tonight's build (I've no idea if CEC still works) I've uploaded a special build #1018x for RPi2 [here](http://milhouse.libreelec.tv/builds/testing/RPi2/LibreELEC-RPi2.arm-8.0-Milhouse-20161018172302-%231018x-gdc3b078.tar) - @DaveTBlake can you give it a spin?

**Comment by DaveTBlake** [comment] 2016-10-18 17:14
Thanks @MilhouseVH will do.
But before that I did one more power cycle test (running 1015), sadly with debug off as wanted to watch video, and CEC came to life. I have been trying most of the afternoon, I'm sure I did this sequence before just this time CEC worked. Go figure?

The sequence - power every thing off at plug; Start TV on other HDMI source; power up Kodi; Switch TV to the HDMI source Kodi on.

**Comment by DaveTBlake** [comment] 2016-10-18 17:15
@opdenkamp what power cycle sequence(s) would you like me to get debug logs for?

**Comment by opdenkamp** [comment] 2016-10-18 17:35
from whatever doesn't work for you ;)
so did reverting this PR work for you?

**Comment by DaveTBlake** [comment] 2016-10-18 18:02
Works briefly.... Then again CEC had started to work before I updated with the revertion (see previous post). Not sure I can say that the revert helped or not. It is like out of 20 times power cycle I might get CEC once.

What can you see from this
Log part 1 http://pastebin.com/SBe2T3gZ
part 2 http://pastebin.com/gkz67seE
had to split for pastebin limits.

What I did:
Install 1018y (while TV on and CEC randonly working). CEC continues to work.
So from working CEC (with revert) I did my night routine - TV in standby leave RPi as is and Kodi to sleep, wait 15 mins, then bring TV out of standby. It says it has CEC to "recorder 1", that is Kodi, but screen remains blank. Touch keyboard to wake up Kodi, but remote keys don't do anything.
CEC broken.
Then thinking test over, and family wanting TV, I started my PVR, also CEC enabled on 2nd HDMI port. TV stayed on Kodi screen an put up CEC message. CEC then works on Kodi.

Sorry if this is not the cleanest of testing. Off for meal now so will be back tomrrow. Your assistence with this much appreciated.

**Comment by opdenkamp** [comment] 2016-10-18 19:05
So this log shows that the TV is working fine, until the point where it says `reconnecting to the CEC adapter after standby mode`. The TV then no longer responds to anything (transmission are not acked).

If you can reproduce this by making it work after a power cycle of the Pi, then it's probably this standby/resume that's killing things for you.

@popcornmix could calling https://github.com/Pulse-Eight/libcec/blob/master/src/libcec/adapter/RPi/RPiCECAdapterCommunication.cpp#L261 a second time after the resume be causing trouble? https://dl.dropboxusercontent.com/u/59212404/dave.log line 251 (filtered log)

**Comment by popcornmix** [comment] 2016-10-18 20:12
I wouldn't recommend calling InitHostCEC a second time.
It does reinitialise the vchiq communication channel that the cec callbacks are transmitted through, without stopping/starting the cec service.

In fact I'm not sure that function needs to be called at all.
You call bcm_host_init() which does:
https://github.com/raspberrypi/userland/blob/master/host_applications/linux/libs/bcm_host/bcm_host.c#L95
so should be handling that for you.

The standby you refer to - is this just TV standby, or is this the Pi suspending?

The thing is Pi doesn't really support suspend. There is no suspend option on stable OE/LE builds (the Pi can't wake up again). Milhouse builds do include a "virtual suspend" feature which just stops driving the HDMI output, but Kodi continues running until a keypress is received.
But this won't have been in @DaveTBlake 's tests with non-Milhouse builds.

Personally I'd have thought calling bcm_host_init (and the stuff in CRPiCECAdapterCommunication::Open to get the cec callbacks) at start, and bcm_host_deinit at exit would be enough. Don't do anything for suspend/resume - it doesn't really exist.

**Comment by opdenkamp** [comment] 2016-10-18 20:49
The PC's standby, and it's Kodi that signals this: https://github.com/xbmc/xbmc/blob/master/xbmc/peripherals/devices/PeripheralCecAdapter.cpp#L194

It simply closes libCEC and opens it again.

@DaveTBlake you can test if this fixes it by #ifdef'ing that part out for the Pi

**Comment by opdenkamp** [comment] 2016-10-18 20:50
I'll change the code to use `bcm_host_init()` only btw

**Comment by popcornmix** [comment] 2016-10-18 20:52
I don't have a CEC TV here, but I have a CEC capable receiver.
I can confirm that cec-client still seems to work with InitHostCEC removed.

**Comment by popcornmix** [comment] 2016-10-18 20:57
From the logs I could see "POLL not sent" was the start of the differences.
I couldn't tell exactly what failed.
Do you know if cecservice_send_command returned an error?
Did it send okay but no callbacks occurred?
Did sending and receiving appear to work, but for some reason TV wasn't happy?

**Comment by opdenkamp** [comment] 2016-10-18 21:10
Then we need a log from this with `#define CEC_DEBUGGING 1` set :)

**Comment by opdenkamp** [comment] 2016-10-18 21:18
I'll do some more testing with this tomorrow. I should be able to reproduce this with cec-client's `r` command, which (pretty much) does the same thing as Kodi does here.

**Comment by MilhouseVH** [comment] 2016-10-18 22:20
libcec won't build with `-DCEC_DEBUGGING=1` - maybe the debugging code has rotted?

x86: http://sprunge.us/BOMa
RPi2: http://sprunge.us/TGLH

If you would like anything tested and need me to provide a build, I prefer patches rather than instructions otherwise you'll never know for sure what is being tested (I have an amazing ability to cockup the most basic instructions)... The patch doesn't have to be a github commit - any sort of pastebin-type link will work for me, as long as it applies cleanly...

**Comment by DaveTBlake** [comment] 2016-10-19 08:48
In an attempt to show if the revert of 9ddb93b helped at all I have gone back to LE 7.90.007

I can now get some consistent behaviour, well I have repeated it at least once, and I believe I get the same with 007 and with the revertion.

From power up (at plug), I need to power TV first then the Pi with the TV with a different HDMI port selected. When I switch to the Pi HDMI CEC then identifies OK and works. But if TV goes into standby and Kodi  sleeps (not the Pi just Kodi screen saving mode), then on bringing TV out of standby although it lists the Pi as a CEC device it does not work from the remote. However if I then start my Humax PVR, another CEC device, the TV suddenly sees the Pi CEC too.

Log of this here http://pastebin.com/rFGSbrqb
- getting CEC to work on RPi by starting up another CEC device.

This is a change from my experiences with OE 5.95.2 last year, and yes it does seem to be  standby/resume related. I hope that the above sequence is revealing in some way.

All your help much appreciated. Ready to test anything that @MilhouseVH can build for me :)

**Comment by opdenkamp** [comment] 2016-10-19 08:53
Right, so it's this (fake) standby/resume that's causing this indeed then, thanks :)

Could you capture a log in which it breaks after resuming and then start that Humax, so I can see what it's doing when it starts to work

**Comment by DaveTBlake** [comment] 2016-10-19 08:56
That behavior is in the above log from 9:14 onwards when I brought TV out of standby this morning.

**Comment by opdenkamp** [comment] 2016-10-19 08:57
Sorry, I meant the Pi, not the TV

**Comment by DaveTBlake** [comment] 2016-10-19 09:05
Sorry, bit confused.
In log you have CEC working (watching video last night), then TV into standby at 22:26 with Pi/Kodi left on over night. At 9:14 TV is brought out of standby and Kodi resumes, but remote not do anything. At 9:15:20 I turned on the Humax, then I navigated Kodi menu using CEC.

I think that is what you are asking about, or something else?

**Comment by DaveTBlake** [comment] 2016-10-19 09:08
Ah just had to commit that pastebin again to confirm not robot, maybe you didn't see it?

http://pastebin.com/rFGSbrqb shows what you ask for I think

**Comment by DaveTBlake** [comment] 2016-10-19 09:14
I never put Pi into standby, I don't think it has one. I leave it on with Kodi in screen saver mode as no convenient way to stop and start - Kodi can power down, but then I have to faff with plug for Pi to get it to restart. Groping for plug is too much effort!

**Comment by MilhouseVH** [comment] 2016-10-19 09:14
> Right, so it's this (fake) standby/resume that's causing this indeed then, thanks :)

In case there's any confusion 7.90.007 has no support for the fake RPi standby/resume feature that disables power to the HDMI socket.

**Comment by opdenkamp** [comment] 2016-10-19 09:14
right, then that is another issue :)

Kodi isn't doing the standby/resume thing that broke things in yesterday's log. The TV wasn't responding at all in there. It wasn't acking transmissions sent to it according to the log, but that may have been a problem with the `bcm_host_init()` stuff.

What's happening here is that the TV powers up, triggers HPD and broadcasts it's physical address. libCEC isn't picking that up as the TV being powered on, and only notices it when the TV routes to HDMI 1 (`0f:80:00:00:10:00`).

In this situation, it's also going to work again if you select the device in the TV's sources list

**Comment by DaveTBlake** [comment] 2016-10-19 09:16
> In this situation, it's also going to work again if you select the device in the TV's sources list

No it doesn't, I tried that. Only starting Humax kicks it into working.

**Comment by opdenkamp** [comment] 2016-10-19 09:17
I'll make libCEC send a power status request to the TV when the TV broadcasts it's address, that should fix the power on thing for you.

| No it doesn't, I tried that. Only starting Humax kicks it into working.

Did you try that with this last build, without standby/resume from Kodi?

**Comment by DaveTBlake** [comment] 2016-10-19 09:18
I think I did, but I will go do it again.

**Comment by opdenkamp** [comment] 2016-10-19 09:19
I'm pretty sure that it'll work ;) If not, route to the TV's internal input or another HDMI input and back, and check if that works. Then pb another log please.

**Comment by DaveTBlake** [comment] 2016-10-19 10:21
http://pastebin.com/KR2QUTeY

At 10:47 TV brought out of standby onto HDMI with Pi, "recorder 1 " came up on screen as the selected device and Kodi screensaver stopped (screen brightens), but remote keys do nothing.
Try TV sync menu to select CEC device, but none are listed.
Put TV back in standby and back, nothing detected on HDMI.
Turn on Humax, and CEC starts to work.
Turn off Humax
TV into standby.
 --- Figure I may have misunderstood what you want me to test!
So start again from "morning" state e.g.  CEC working last time, TV in standby, Kodi in screensave
At 11:10 TV brought out of standby (same as 10:47)
Change TV source to different HDMI
Change TV source to own tuner
Change TV source to pi, still id as "recorder 1", but remote not work (Kodi in screen save)
Try TV select CEC device as "recorder 1", it is in list, but get message "communication failed"

**Comment by DaveTBlake** [comment] 2016-10-19 14:21
@opdenkamp let me know if I managed to produce a useful log, or you need something else. 
The family will be running LE 7.90.007 this evening, I can try to test around them.

**Comment by opdenkamp** [comment] 2016-10-19 14:22
I couldn't repro it with cec-client/libCEC only. checking kodi's implementation atm

**Comment by DaveTBlake** [comment] 2016-10-19 14:26
Thanks. At least I have a repeatable situation now, or I hope it is.

**Comment by DaveTBlake** [comment] 2016-10-20 08:18
Tried to turn debug on for CEC without being obtrusive on screen adding
```
<loglevel>1</loglevel>
  <debug>
      <extralogging>true</extralogging>
      <setextraloglevel>32768</setextraloglevel>
      <showloginfo>false</showloginfo> 
  </debug>
```
to advancedsettings.xml
But not getting the same message output in the log. Is there a way to do this or do I need to keep using the on screen settings?

**Comment by opdenkamp** [comment] 2016-10-20 08:19
I've never looked into the possibility of getting debug output in a release build without the popup, sorry :)

**Comment by MilhouseVH** [comment] 2016-10-20 09:18
`libCEC` component logging has a value of 16384.

This should work in advancedsettings.xml:
```
  <loglevel>1</loglevel>
  <debug>
      <extralogging>true</extralogging>
      <setextraloglevel>16384</setextraloglevel>
      <showloginfo>false</showloginfo> 
  </debug>
```

**Comment by DaveTBlake** [comment] 2016-10-20 15:22
After retesting with LE7.90.007 I find that if I don't turn on my Humax as well then I can't get CEC to work. I had thought I had managed without that 2nd device at some point, but I can't repeat it now. 

Sequence (with no Humax):
Every thing off at the plug.
TV power on, wake out of standby.
Switch to HDMI of Humax even though Humax is in standby
OR
Leave TV on HDMI port of Pi
Power up Pi at plug
Switch TV to HDMI port of Pi (if not on it already)
Kodi on screen, Pulse Eight message pops up.
TV has no CEC devices Sony in "Sync" menu
Remote does not effect Kodi.

Log of all this here http://pastebin.com/B6GaXN8w

Is there anything else I can try?

**Comment by opdenkamp** [comment] 2016-10-20 15:24
Not at this time, need to get some stuff committed first, thanks :)

**Comment by DaveTBlake** [comment] 2016-10-21 08:48
Sorry for being over enthusiastic :)

Wierd one last night: got CEC working by having Humax on, then turned Humax to standby. CEC to Pi keeps working while watch a few video files, but at the end of the 2nd it nolonger worked. So turn Humax back on, CEC works. Turn Humax to standby and keep using CEC, but again after 1hr or less it stops. Some kind of timeout??? I have a log for this, but quite big so not sure you wil be able to spot anything, or even if you will want to try?

**Comment by opdenkamp** [comment] 2016-10-21 08:50
Sure, upload it please and tell me around which time I need to look, can be useful. Thanks

**Comment by DaveTBlake** [comment] 2016-10-21 09:40
Log large, video with sync issues,  so in dropbox https://www.dropbox.com/s/pzvblmpfh4oylwd/kodi21_04_36.log?dl=0

Having used CEC to select what to play (episodes of "Bones") at 20:26 and 21:09, discovered that CEC had stopped working at the end of playback at 21:55. So 21:56 we woke the Humax and CEC works again. End of playback e19 at 22:45 CEC has stopped again. Put TV in standby and go to bed.
Notice at 2:57 have some CEC activity, not sure why.
Same at 4:36 "Tuner 1" is what the TV calls the Humax. I guess the Humax does something to update EPG etc. and TV sees activity?

**Comment by opdenkamp** [comment] 2016-10-26 15:25
I've addressed the `bcm_host_init()` calls after standby, but something else is wrong here.

Everything is working fine and keys are received until 21:29:45. Then the video player does a `GENERAL_RESYNC` and starts spamming calls to adjust the HDMI clock according to this log
I remember @popcornmix telling me that CEC shares the same clock, and I can see that the TV is treating the Pi as a new source device after the video stopped, indicating that CEC wasn't working while the video was playing. Once the clock adjustments stopped, libCEC sends an active source message, and CEC starts working again.

@popcornmix correct me if I'm wrong, but this appears something that's caused by these clock adjustments and CEC simply can't work correctly because of how the hw works. Stopping these adjustments (presumably sync to display setting in Kodi) would fix this.

**Comment by popcornmix** [comment] 2016-10-26 20:50
There are two hdmi clocks on Pi. HDMI state machine clock and pixel clock.
The audio and CEC runs off state machine clock and the video off the pixel clock.
The clock adjustment only affects the pixel clock, so I couldn't imagine it affecting CEC.
Also max adjustment is < 0.1% which is within the HDMI clock tolerance.

With out of the box settings, the pixel clock isn't adjusted.
With omxplayer enabled it will only be adjusted when sync playback to display is enabled.
With omxplayer disabled (default) it will only be adjusted when "PLL adjustment to maintain audio/video" is enabled (disabled by default).

@DaveTBlake Can you confirm you have the issue with "PLL adjustment" set to "off" and omxplayer disabled?

**Comment by popcornmix** [comment] 2016-10-26 21:10
Okay, I've double checked and the omxplayer case is as described, but the mmal case can adjust PLL when sync playback to display is disabled which wasn't what I'd thought. I'll change that for the next test build.

@DaveTBlake For now can you enable omxplayer and disable "adjust display refresh rate" and test CEC and see if that makes any difference?
With tomorrows build, you can test with omxplayer disabled and "sync playback to display" disabled which shouldn't have any "CRBP::AdjustHDMIClock" messages in log.

**Comment by opdenkamp** [comment] 2016-10-26 21:24
Thanks for looking into this :)

**Comment by opdenkamp** [comment] 2016-10-26 21:25
And for the explanation :)

**Comment by DaveTBlake** [comment] 2016-10-28 07:53
All my logs so far have been with "PLL adjustment" set to "off" and omxplayer disabled.
Initial CEC tests also had "adjust display refresh rate" off too, but mostly it is enabled. Maybe that has contributed to varying CEC behaviour, I'm unsure so will test.

**Comment by opdenkamp** [comment] 2016-10-28 08:04
Please upload another log if this still happens with Milhouse's last build

**Comment by DaveTBlake** [comment] 2016-10-28 08:12
OK, I'll see if I can get CEC working without the Humax with latest build.

**Comment by DaveTBlake** [comment] 2016-10-28 14:00
Tried Millhouse build 1027, just as before CEC only works when I have my Humax on too. Once CEC is working I can turn the Humax off, but after time or TV in standby then wake up CEC does not work. 

Would you like more logs? And do you want me to try the various combinations of video settings?

**Comment by opdenkamp** [comment] 2016-10-28 14:03
No idea what version of the PR and lib @MilhouseVH included in that build :) libCEC has been tagged for 4.0.0 now, so that should be the one to use, with the current version of the PR.

Please post a new log in which it breaks, and leave the Humax disconnected please.

**Comment by DaveTBlake** [comment] 2016-10-28 14:14
The build has LibCEC 4.0.0. Current logs have me turn on Humax at some point to check that behaviour, I will reboot without. But no Humax, I see Pulse Eight messages on screen, but TV does not see Pi as a CC device.

**Comment by opdenkamp** [comment] 2016-10-28 14:17
It may say 4.0.0, but that bump happened a couple of days ago, before it was tagged and the PR for Kodi got updated too. So you may be testing an incomplete version.

**Comment by opdenkamp** [comment] 2016-10-28 14:20
Please power off the TV and power it back on too after changing connected HDMI devices btw. I could be some cached value in the TV

**Comment by DaveTBlake** [comment] 2016-10-28 14:23
OK, power cycles for all concerned :)
Millhouse build 1027 was from yesterday, it includes libcec master cf438566 (ahead +49). Is that sufficiently current? Otherwise I will have to wait for @MilhouseVH to kindly build something for me.

**Comment by opdenkamp** [comment] 2016-10-28 14:26
Yeah that's recent enough. I've just updated the readme files after that commit yesterday evening.

**Comment by DaveTBlake** [comment] 2016-10-28 14:44
Debug http://pastebin.com/1vy0WhPf

Humax is off.  Power up TV from socket. Power up Pi. See pulse Eight message. But CEC not work, TV not see any CEC device. Put TV into standby. Didn't do any actions in Kodi.

**Comment by opdenkamp** [comment] 2016-10-28 14:55
```
15:35:59  11.644827 T:1796658080   DEBUG: CecLogMessage - processor thread started
15:35:59  11.645170 T:1796658080   DEBUG: CecLogMessage - << Broadcast (F) -> TV (0): POLL
15:35:59  11.645301 T:1796658080   DEBUG: CecLogMessage - initiator 'Broadcast' is not supported by the CEC adapter. using 'Free use' instead
15:35:59  11.645402 T:1796658080   DEBUG: CecLogMessage - << e0
15:36:00  12.645759 T:1796658080   DEBUG: CecLogMessage - command 'feature abort' timeout
...
15:36:04  16.242216 T:1796658080   DEBUG: CecLogMessage - AllocateLogicalAddresses - device '0', type 'recording device', LA '1'
15:36:04  16.242403 T:1796658080   ERROR: CecLogMessage - RegisterLogicalAddress - vc_cec_set_logical_address(1) returned device is busy (3)
15:36:04  16.242441 T:1796658080   DEBUG: CecLogMessage - UnregisterLogicalAddress - releasing previous logical address
15:36:04  16.242647 T:1796658080   DEBUG: CecLogMessage - logical address changed to Broadcast (f)
```

That's the first issue again, not the same one as in https://github.com/Pulse-Eight/libcec/issues/252#issuecomment-255338553

First we attempt to poll the device on address 0 (the TV), which times out for some reason (should have been ack/no ack) and then we attempt to assign address 1 to the Pi, but we get an EBUSY returned from the Pi's firmware.

@popcornmix why would a transmission time out like that? It's the first thing that we attempt to do after starting. How/why does `vc_cec_set_logical_address()` return busy?

**Comment by Kwiboo** [comment] 2016-10-29 04:42
From what I can tell the Humax could be running an Amlogic chip and there is issues with Amlogic's u-boot CEC code that causes interfere with the CEC communication for all connected devices once the device in in standby mode. The hw chip gets stuck after some tx/rx and seems to hog the hdmi cec line.

For the Odroid C2 I modified the u-boot code with https://github.com/Kwiboo/u-boot/commit/005dc1f22f3d3097dbabc6d25cc6e3b54741671b, an earlier version of this is already upstream in hardkernel's u-boot but almost all other Amlogic S905 devices I have tested causes this type of cec interference. As soon as the hdmi cable is disconnected from the Amlogic device CEC starts working for all other devices.

**Comment by opdenkamp** [comment] 2016-10-29 09:00
Ah I didn't think of that, because of how the error log looked, but that's a good possibility indeed. Our usb-cec adapter would be complaining (low error, high error, timeout) in the error log, but I've never tested what happens in this situation with the Pi.

Did you try to disconnect that Humax from HDMI @DaveTBlake?

**Comment by DaveTBlake** [comment] 2016-10-29 09:10
Yes, interesting. Unwired the Humax, and power cycled everything, and LibCEC (4.0.0) on Pi is working. So yes the Humax even in standby seems to be the culpret.

Having had no CEC with OpenElec and **before I owned the Humax**, and been through all the hardware combination checks with cable, HDMI ports etc. I guess I was less thorough this time. Updating to RPi3 and LibreElec, and seeing some CEC got me over excited. And of course I have not tested what happens with LibCEC 3.0

**Comment by DaveTBlake** [comment] 2016-10-29 09:13
Like to see a log of CEC working? :)

And of course I have to ask if anything can be done to LibCEC to make it robust against the AmLogic chip bad behaviour? I do want to have my Humax back on as well as Kodi.

**Comment by opdenkamp** [comment] 2016-10-29 11:28
Not needed, thanks.

This is not something that can be addressed in anything other than the Humax itself.
e.g. if I tell the usb-cec adapter to pull the cec line low, I will break cec for all other devices that are connected to hdmi.

The only work around is buying one of the cec-less hdmi cables from our webshop, and connect it between the Humax and TV. This way cec will work for the Pi and TV and the broken device will be prevented from breaking anything else.

Thanks for testing, and good to know what's causing this kind of behaviour from the Pi's firmware.

**Closed by opdenkamp** 2016-10-29 11:28 UTC

**Comment by DaveTBlake** [comment] 2016-10-29 11:49
Many thanks for your assistance with this. Sorry to have had you digging in code for something that turned out to be external. I had assumed my original CEC problems and current ones were more related than they turned out to be. My bad - new Pi, new Kodi, new Humax, only thing the same was the TV!  I should have been more systematic

The effects of the interaction are odd though. I will put details on the foum in case it can help others in future.

**Comment by popcornmix** [comment] 2016-10-29 12:09
@opdenkamp 
```
vcgencmd set_logging level=0x100000
# do some CEC/HDMI operations
sudo vcdbg log msg
```
will get some logging messages out of gpu. I suspect if you are seeing VC_CEC_ERROR_BUSY
then there may be a "CEC: Device is busy, not setting logical address passively" in log.
I assume this means the previous CEC command hasn't had a response?

**Comment by opdenkamp** [comment] 2016-10-31 10:06
I'd have to try to reproduce this while forcing the usb-cec adapter to break the cec line. @DaveTBlake could you run `vcgencmd set_logging level=0x100000`, reproduce the issue with the Humax connected, and then send the output of `sudo vcdbg log msg` to @popcornmix? Thanks

**Comment by Kwiboo** [comment] 2016-10-31 10:45
@DaveTBlake to clarify Amlogic devices only interfere with cec communication when they are in standby/power off mode and uses the bad cec handling in u-boot firmware code, when they are powered on and running linux/android on main cpu there should be no more interference with cec communication.

**Comment by DaveTBlake** [comment] 2016-10-31 10:53
@Kwiboo that does match my experiences, thank you for spotting this as the cause. This lower level stuff is beyond my knowledge, but I have been thinking about raising the issue with Humax too. Can you provide any references I can share with them to help explain what we think is happening?

@opdenkamp need a bit of hand holding to run what you ask. Using SSH to move files about is my limit with the Pi.

**Comment by opdenkamp** [comment] 2016-10-31 17:46
It's not an uncommon issue, and my bad that I didn't think about this earlier, but I never tried this on the Pi and it's producing different logging.

re logging: just type those commands in ssh, assuming that openelec/libreelec included them

**Comment by DaveTBlake** [comment] 2016-10-31 18:21
Got my head around logging now, but a bit unclear exactly what sequence of Humax/Pi CEC interaction will be most useful to you.

I was thinking you wanted to see the gpu logging while I had generated a  "ERROR: CecLogMessage - RegisterLogicalAddress..." in Kodi. But that only seems to occur when I reboot Pi with Humax in standby, but the Pi it loses the vcgencmd logging setting on reboot.

If you could get your hands on my system, what would you do?

**Comment by opdenkamp** [comment] 2016-10-31 19:04
That's indeed the type of logging that we're looking for, to see what it's doing when another device is breaking CEC. Would be nice to warn about this in the log so we can see what's causing the trouble.
And if I could do it, then I would do exactly that, boot the Pi with that Humax in standby ;)

**Comment by popcornmix** [comment] 2016-10-31 19:06
> But that only seems to occur when I reboot Pi with Humax in standby, but the Pi it loses the vcgencmd logging setting on reboot.

Are you sure Pi needs a reboot - perhaps just kodi restarting would be enough?
```systemctl restart kodi```

**Comment by opdenkamp** [comment] 2016-10-31 19:09
Restarting Kodi would be enough indeed. It'll start address allocation and will fail then

**Comment by DaveTBlake** [comment] 2016-10-31 20:03
Right all I have to do now is reproduce the sequnce of wake/sleep that causes the  "ERROR: CecLogMessage - RegisterLogicalAddress..." message. Proving more elusive than I thought :(

**Comment by opdenkamp** [comment] 2016-10-31 20:05
If it's this issue that we expect it is, then putting the Humax in standby and restarting the Pi or Kodi would cause the problem.

**Comment by DaveTBlake** [comment] 2016-10-31 23:17
Yes I thought so too, and I have previous logs with  "ERROR: CecLogMessage - RegisterLogicalAddress..." on LibCEC 4.0 and the current build that look like they occur just after Kodi boot. It is just my attempts to repeat it (with gpu logging on) have caused CEC to stop, but haven't so far produced that error in the  Kodi log. It could be that the Humax was not sufficiently in standby. 

I'll keep trying and let you know if I get something to look at.

**Comment by DaveTBlake** [comment] 2016-11-01 09:16
OK, after an overnight delay (so Humax probably did something while in standby) I did a reboot of Kodi and got a  "ERROR: CecLogMessage - RegisterLogicalAddress..." in the debug

gpu log here http://sprunge.us/beKd @popcornmix get anything from this?

**Comment by popcornmix** [comment] 2016-11-01 11:47
@DaveTBlake Nothing in log. Looks like the vcgencmd wasn't run.
Did you run the vcgencmd before the  "ERROR: CecLogMessage - RegisterLogicalAddress..." appeared in log, and the vcdbg after it appeared (without rebooting the pi in between)?

**Comment by DaveTBlake** [comment] 2016-11-02 17:24
I have not power cycled the Pi at all.  But there was 12 hours or so gap between running vcgencmd and before rebooting Kodi produced the error. I then ran vcdbg and pasted the result. But does rebooting Kodi/LE reset the setting?

I'll try again. So sorry if this is my incompetence somehow.

**Comment by DaveTBlake** [comment] 2016-11-07 18:42
Guys I am unable to create a  "ERROR: CecLogMessage - RegisterLogicalAddress..." entry in the debug log without rebooting Kodi from the main screen. Just doing `systemctl restart kodi` is not enough. Of course doing this clears the vcgencmd setting, so I have not managed to capture a gpu log to go with this event.

Does the difference between restart and reboot tell you anything about the bad behavioir of the Amlogic chip, or how LibCEC could maybe cope with it?

**Comment by opdenkamp** [comment] 2016-11-08 08:36
Can you upload logs from both situations please, with that Humax in standby. No idea what's different for you.

I'm just wondering what's happening exactly there btw, so we can detect this problem on the Pi. We can't fix the issue with the Humax for you. You can only fix it by using an HDMI cable without a CEC wire between the Humax and the TV, which we sell in the webshop.

**Comment by DaveTBlake** [comment] 2016-11-12 11:20
Sorry for delay, but at least I think I may have captured the GPU log that goes with a "ERROR: CecLogMessage - RegisterLogicalAddress..." message :)

I know you can't fix the Humax issue, and I can live with working around it turning it on to use CEC on Kodi. But it would also be good for you to know what is happening on the Pi. 

With TV on and Humax in standby, I rebooted Kodi from main screen. The log showing the   "ERROR: CecLogMessage - RegisterLogicalAddress..." message is here http://pastebin.com/B23dHZjy

If I then restart Kodi I found I also get that error message (if I restart from a previously working CEC then I don't, or at least I think that is why I don't always get the error on a restart). So I turned on GPU logging `vcgencmd set_logging level=0x100000` and did `systemctl restart kodi` . 
The Kodi log is here http://pastebin.com/z5rnvcs6
The GPU log is http://sprunge.us/AYDJ

I hope I have captured something useful.

**Comment by popcornmix** [comment] 2016-11-12 15:45
Thanks @DaveTBlake that does include the "CEC: Device is busy, not setting logical address passively" error in log, although there have been a number of previous errors before that.
I don't really know enough about the mechanics of CEC to say exactly what is happening, but I'm guessing we are just not seeing anything on CEC bus (perhaps because Humax is holding the line high or low), so get no responses.

I have checked the firmware code and I think you can add:
``logging_level=0x100000``
to config.txt and that will act the same as the vcgencmd, but will work straight from boot, so may provide a more useful log.
