### ISSUE TITLE
TV changes input when turned on

### ISSUE THREAD

**Issue by ashtonaut** [Pulse-Eight/libcec#307] opened 2017-02-12 06:21 UTC
**Issue:**
- When the TV is turned on, after 5 seconds, it automatically switches input to the Raspberry Pi, without any user input. The Raspberry Pi is left on at all times, so this is not related to the Pi turning on.

**To reproduce:**
1. Leave RPi running
2. Switch TV to broadcast input, and put TV into standby
3. Bring TV out of standby using TV remote
4. TV will turn on, and after 5 seconds automatically switch to the RPi HDMI input

**Hardware:**
- LG 42LM6410
- Raspberry Pi 3
- HDMI connection between Pi and TV

**Software:**
- RPi running OSMC 2017.02-2
- Issue started with OSMC 2017.02-1 (the Krypton update)
- The issue appears linked to the updated version of libcec that is bundled with Kodi Krypton (4.x?)
- This has never occurred and never been an issue in any previous version of OSMC (or Raspbmc)

**Related forum posts:**
- [This forum post](https://discourse.osmc.tv/t/tv-auto-switches-to-osmc-when-turned-on/22266/4?u=ashtonaut) outlines the issue, and includes a [debug log](http://paste.osmc.io/jicipihopa) from OSMC
- [This forum post](https://discourse.osmc.tv/t/tv-auto-switches-to-osmc-when-turned-on/22266/19?u=ashtonaut) includes a log capturing cec-client output while reproducing the issue
- Finally, [this post ](
https://discourse.osmc.tv/t/tv-auto-switches-to-osmc-when-turned-on/22266/24?u=ashtonaut) includes a link to [this debug log](http://paste.osmc.io/iqeqociwot), this time with component-specific logging enabled for libcec

**Other thoughts**
- The OSMC devs have looked at the issue and suggest that it's something that needs to be raised here.
- There are at least 3 OSMC users reporting this issue
- The issue appears to be specific to LG TVs _(edit: it appears to be wider than just LG, and also wider than just TVs)_
- I suspect that either the Pi is sending some kind of signal it shouldn't be, or (perhaps more likely, given LG's CEC implementation) the TV is incorrectly picking up something the Pi is sending and changing input when it's not supposed to.

The WAF is at an all time low, so I'm desperate for some help here...

Thanks in advance for any thoughts or help.

**Comment by ashtonaut** [comment] 2017-02-13 04:46
Per the OSMC thread on this issue (linked above), this appears to be affecting things other than just LG TVs. The issue has been reported with a Panasonic TV and a Denon receiver as well.

**Comment by popcornmix** [comment] 2017-02-14 14:30
Possibly this issue: https://github.com/raspberrypi/firmware/issues/739
Can you try downloading updated firmware:
https://github.com/raspberrypi/firmware/blob/master/boot/start_x.elf?raw=true
https://github.com/raspberrypi/firmware/blob/master/boot/fixup_x.dat?raw=true
and replace the ones on your osmc sdcard (the directory visible when sdcard is inserted in windows)

**Comment by mcobit** [comment] 2017-02-14 16:17
With this firmware the lockup of cec when applying settings still persists.
And the switching also still occurs.

**Comment by ashtonaut** [comment] 2017-02-15 09:52
If there is value in me testing that firmware as well I'm happy to, though given mcobit's response I suspect it won't fix it. I will try when I next get a chance and report back.

**Comment by popcornmix** [comment] 2017-02-15 19:40
@ashtonaut It's worth trying. There may be more than one issue at play here.

**Comment by ashtonaut** [comment] 2017-02-16 06:11
@popcornmix I tried replacing the firmware files with the two you linked to.

Aside from some unexpected changes to the Estuary skin (main menu items I had previously turned off turned back on), no change to this issue:

- TV still auto switches to RPi HDMI input when it shouldn't
- CEC hangs and is unresponsive after selecting OK in the CEC settings dialogue

This is following several reboots of both RPi and TV, including a 60 second cold shutdown of the TV.

**Comment by ashtonaut** [comment] 2017-02-21 06:56
If anyone has any ideas for further testing, debugging, other things to try, or information to provide, please let me know.

**Comment by Stane1983** [comment] 2017-02-24 02:30
I'm not sure if it's related but Amlogic's AOCEC implementation suffers from similar issue when switching sources on TV. If you're in Kodi and CEC is active (libcec version 4.0.4; not LE/OE but Buildroot based) if you switch source from input where your device is to TV directly (not via menu but separate TV button which is basically antenna input) CEC on device instantly switches back to HDMI input. But when navigating trough sources menu on TV remote and manually select antenna input as active source it stays there.

**Comment by samnazarko** [comment] 2017-02-24 02:33
This seems to have been identified as a problem with Raspberry Pi firmware currently.

We have not seen this issue on Vero 4K (AOCEC implementation).

**Comment by ashtonaut** [comment] 2017-02-25 02:19
Oh well, good to hear it's being looked at. Thanks.

**Comment by FutureSharks** [comment] 2017-03-12 23:23
Any update on this issue? I have it too, quite annoying. Is there a corresponding issue in the raspberry pi project? The issue linked above is a separate problem I think.

**Comment by ashtonaut** [comment] 2017-03-13 05:58
I'm not sure where this issue has been picked up - perhaps @samnazarko or @popcornmix can point somewhere? I can't see anything obvious in the Raspberry Pi firmware issues list, but I'm aware there are a few different CEC issues being worked on at the moment.

**Comment by mcobit** [comment] 2017-03-21 09:57
This is definately not an issue with the firmware on raspberry as it also happens on a girmware from before the recent cec changes took place.

**Comment by mcobit** [comment] 2017-03-21 09:58
Happens since Kodi 17 update that pulled in libcece 4

**Comment by anomaly256** [comment] 2017-03-30 00:37
I am having this same issue but with a pulse8 usb adapter and kodi v17.  v16 worked fine and did not do this.  I've disabled everything in the input peripheral configuration that has anything to do with changing inputs and it still happens every time I turn my TV on (LG 60LM6450 btw)

**Comment by anomaly256** [comment] 2017-04-08 10:08
@samnazarko would mine possibly be a related problem or do you wish me to open a new issue for it?  Exact same symptoms but no rpi in the setup at all.

**Comment by popcornmix** [comment] 2017-04-08 11:22
@anomaly256 
Initially the issue was thought to possibly be either a pi firmware issue or a libcec 4 issue.
As the problem still occurs with previous pi firmware, appears when updating from libcec 3 to libcec 4 and occurs on other platforms I think we safely can say it is a libcec 4 issue, and this is the right place for your report.

**Comment by anomaly256** [comment] 2017-04-08 14:16
@popcornmix ok no worries, thanks

**Comment by samnazarko** [comment] 2017-04-09 16:52
Indeed, it looks like this issue is a problem with libCEC4 as we have seen this on other platforms now.

**Comment by anomaly256** [comment] 2017-04-10 01:13
I notice my adapter is on V4 firmware, and there appears to be no upgrader for later firmware versions available anywhere except for Windows.  Should I upgrade to V7 from a Windows machine before reporting/testing/bug hunting this problem?

**Comment by mfarrell34** [comment] 2017-04-17 22:48
I reproduced this as well and saw similar logging messages to those included in the initial post. In particular the TV is sending vendor command 0b to the raspberry pi after its power status changes to "on". For the LG TV command handler, CSLCommandHandler, this is interpreted as a reconnect request and the handler method HandleVendorCommandPowerOn is called in response. Unless I'm missing something this method call seems to be responsible for LibCEC setting the active source to the Pi which also changes the input on the TV to the port the Pi is connected on. 

Not sure if it's unexpected for the TV to be sending the reconnect request in this scenario or not, can anyone comment on this? The power status of the Recorder 1 (Pi) is already on when this command is received, so it doesn't seem that it should be changing the status back to "in transition from standby to on" and then to "on" after receiving this request from the TV.

**Comment by jfjm** [comment] 2017-04-28 08:09
Looking through the changelog:
https://github.com/Pulse-Eight/libcec/blob/master/debian/changelog.in

 * handling of LG vendor command 0x0B. Issue #256. Credits @Vollstrecker

I highly suspect it is this "fix" that actually created issue for many of us. Please revert back to the behavior prior to the "fix". It was working perfectly before.

**Comment by rrolandd** [comment] 2017-04-28 11:57
If I compile the libcec without those changes, is it possible to replace it somewhere in Libreelec?

I crosscompiled just the libcecm then created .profile file with LD_LIBRARY_PATH="/storage/lib:/usr/lib:/lib" and I placed the dynamic library there:
 425989 lrwxrwxrwx    1 root     root            17 Apr 28 13:36 libcec.so -> ./libcec.so.4.0.2
 425988 lrwxrwxrwx    1 root     root            17 Apr 28 13:36 libcec.so.4 -> ./libcec.so.4.0.2
 425986 -rwxrwxrwx    1 root     root       1161284 Apr 28 12:31 libcec.so.4.0.2

Without any luck :(

**Comment by jfjm** [comment] 2017-04-29 01:58
Did you rebuild the ld cache using ldconfig?

**Comment by rrolandd** [comment] 2017-04-29 05:58
No, I don't :( Milhouse was so kind to make us a build with reverted #256 Here you can get it: http://milhouse.libreelec.tv/builds/testing/RPi2/LibreELEC-RPi2.arm-9.0-Milhouse-20170428184648-%230427l-ga5bf4d2.tar

I will be able to try it tomorrow...

**Comment by maart84** [comment] 2017-04-30 07:09
I installed that build and my LG tv is no longer switching to the RPI when i turn my tv on!

**Comment by ashtonaut** [comment] 2017-04-30 07:25
Sounds promising! @samnazarko any chance you could create something that those of us using OSMC could test?

**Comment by samnazarko** [comment] 2017-04-30 07:26
Sure

I'll update the thread shortly

Sent from a mobile device, so please excuse the brevity of this reply

On 30 Apr 2017, at 08:26, ashtonaut <notifications@github.com<mailto:notifications@github.com>> wrote:


Sounds promising! @samnazarko<https://github.com/samnazarko> any chance you could create something that those of us using OSMC could test?

-

**Comment by rrolandd** [comment] 2017-04-30 17:49
I can also confirm that it solved the issue with the input change when TV turned on and also the play video issue what I had when the video was paused.

**Comment by tvdbergh** [comment] 2017-04-30 19:53
This fix seems to solve the issue for me as well.

**Comment by samnazarko** [comment] 2017-05-01 00:35
In case anyone missed my thread update earlier, see https://discourse.osmc.tv/t/tv-auto-switches-to-osmc-when-turned-on/22266/59?u=sam_nazarko

S

**Comment by ashtonaut** [comment] 2017-05-01 07:15
Sam's updated libcec for OSMC (link in previous comment) appears to have fixed this issue for me.

Thanks to all involved in finding the specific commit that appears to have introduced the issue.

**Comment by anomaly256** [comment] 2017-05-09 08:50
Confirmed that reverting #256 fixes the issue for me

**Comment by anomaly256** [comment] 2017-05-16 05:18
@popcornmix any idea if a decision has been made regarding whether to revert #256 or re-engineer it to solve this problem without unsolving the problem @vollstrecker had originally?  Although I can't replicate @vollstrecker's issue with my TV I'm happy to test or give any other info that might help

**Comment by Vollstrecker** [comment] 2017-05-16 07:31
I'm now able to read the code on a sane device, and I'm a bit confused. SLCommandHandler.cpp:189 checks, if we are the active device, before it sets itself as active source.

**Comment by kkkkamal** [comment] 2017-06-03 08:57
I need to enable simplink on boot automatically. But, currently we have to do it manually every-time from Remote Control using the Settings->Input->Simplink->HDD Recorder.

I have been stuck for almost a week trying to figure out what the issue is. We are using a cec-client to control the LG TV. Is there a way to enable simplink on the TV from the Pi or any methods to enable simplink from the Pi side.

Hardware Used:

Raspberry PI LG Television ( 32LF565B ) Any input is highly appreciated.

**Comment by opdenkamp** [comment] 2017-07-12 11:06
The problems are caused by LG's CEC implementation, which breaks interop with devices that do follow the spec. I've changed this LG code in another CEC implementation, and it no longer switches inputs most of the times, but it's a completely different implementation and can't be backported quickly. I'll have to check this in the next major release.

**Comment by anomaly256** [comment] 2017-07-12 11:28
So, can we get #256 reverted until the new implementation then so the many of us without @Vollstrecker's problem can resume using libcec as we did before that change?  Or are more people than initially reported experiencing @Vollstrecker's without it?

**Comment by anomaly256** [comment] 2017-07-16 23:16
Hi @opdenkamp, I notice you pushed 1a8dc6c96a1c74d2820fea1a39f4dc8057905102 a few days ago to close #344, does this also address this issue?  If not can we get #256 reverted as well?  Thanks

**Comment by anomaly256** [comment] 2017-08-01 00:36
@opdenkamp ?

**Comment by anomaly256** [comment] 2017-08-03 08:21
I guess we can take that as a 'no'.

**Comment by opdenkamp** [comment] 2017-08-03 08:55
Haven't had time to look into this yet.

**Comment by anomaly256** [comment] 2017-08-03 09:48
Ok, thanks for responding.  Just hoping we don't have to wait for a new implementation to land since it was working for most of us prior to that commit

**Comment by opdenkamp** [comment] 2017-08-03 10:02
I'm working on a new release with fixes, but other code has priority atm. I'll get it done asap

**Comment by anomaly256** [comment] 2017-08-03 10:47
Thanks heaps

**Comment by mfarrell34** [comment] 2017-08-04 02:32
Haven't tested it yet but looking at the code it looks like it will resolve this issue. From what I saw when recreating it the only problem caused by #256 was the set active source call, and this call shouldn't be made anymore in this scenario when the 0x0b command is received.

**Comment by anomaly256** [comment] 2017-08-04 02:42
I have tested it and so have others that were reporting on this issue.  Reverting #256 has fixed the problem for us locally.

**Comment by mfarrell34** [comment] 2017-08-04 03:25
You tested after applying the changes in [1a8dc6](https://github.com/Pulse-Eight/libcec/commit/1a8dc6c96a1c74d2820fea1a39f4dc8057905102) and this issue with the TV changing input was still occurring?

**Comment by anomaly256** [comment] 2017-08-04 03:34
Oh sorry I misunderstood, I tested reverting the initial commit, I haven't had a chance to test that new one yet.  I'll try this weekend if I get time

**Comment by mfarrell34** [comment] 2017-08-04 14:05
Actually I got a chance to test it last night and my earlier post was incorrect, the input is still changing after applying the [1a8dc6c](https://github.com/Pulse-Eight/libcec/commit/1a8dc6c96a1c74d2820fea1a39f4dc8057905102) change. I'll turn on logging and reproduce it again to provide more info if that would be useful.

**Comment by stedaniels** [comment] 2017-10-19 20:47
So is the current workaround for this issue to use the build mentioned in https://github.com/Pulse-Eight/libcec/issues/307#issuecomment-298149513 ?
Cheers

**Comment by anomaly256** [comment] 2017-10-19 21:19
On Fri, 20 Oct 2017 at 7:47 am, Steve Daniels <notifications@github.com>
wrote:

> So is the current workaround for this issue to use the build mentioned in #307
> (comment)
> <https://github.com/Pulse-Eight/libcec/issues/307#issuecomment-298149513>
> ?
> Cheers
>
In my case at least, yes it was

**Comment by Stan-Tastic** [comment] 2017-11-24 11:32
The link in #307 is dead, can someone re-upload it?
I have Philips TV, connected via Denon amplituner. The issue doesn't happen always, but quite often.

**Comment by felipesalomao** [comment] 2017-12-29 06:20
Hi, i have raspbian with kodi installed.. never installed libcec manually (i think kodi installed itself).. What exactly i need to change to fix that problem (auto hdmi switch after power on lg tv)? What command use on putty or files to change using ssh? Thanks

**Comment by anomaly256** [comment] 2017-12-29 09:13
We know the fix for this, reverse that broken commit that introduced the problem.  Why hasn’t the fix been merged yet?

**Comment by malard** [comment] 2017-12-29 09:17
i am sorry but we are in a major period of development with our other products ahead of ISE (tradeshow) once that is over we will update libCEC with more improvements, including this

**Comment by anomaly256** [comment] 2017-12-29 09:23
Thanks for the update @malard, glad to hear it.  I'm a little dismayed though that 10 months after being reported a small commit that appears to have served only to introduced breakage for many people while fixing an issue for 1 hasn't simply been reverted.  Kind of scratching my head about the reasoning there :confused:

**Comment by felipesalomao** [comment] 2017-12-29 09:29
While it is not fixed, could you help solve it? I never installed libcec manually, I think kodi installed it. Always when I open kodi I see notification that cec is working.. so I does not know even installation path.. I am running raspberry pi. OS is raspbian.. do you know what files I need to change?! Thank you

**Comment by anomaly256** [comment] 2017-12-29 09:44
@felipesalomao you will need to download libcec sources and either manually undo the changes from commit 9cc4c29 or checkout the commit before that one was merged, compile your modified libcec sources on the device or cross compile for raspberry pi from a PC, then remove the version of libcec.so that Kodi installed and install your newly compiled one in its place.  If this isn't something you've done before you might need to find someone to build you a version for your hardware

**Comment by ronbarr** [comment] 2018-01-27 23:02
As a new user it's a shame that the pi is broken for LG TV users. I can build a custom version but I don't want to have to maintain this over time. 

At least the pi still works as a file server once I disconnect it from the TV.

**Comment by adamhassel** [comment] 2018-02-13 12:18
I just wanna chime in here and say I have the same behavior with an older Samsung TV.

**Comment by anomaly256** [comment] 2018-03-17 10:38
Hi, can you just fricking revert the [expletive] [expletive] [expletive] patch already?  This situation is asinine and your 'next major release' is obviously not here yet.  IT'S BEEN MORE THAN A YEAR.  JUST REVERT IT.

**Comment by anomaly256** [comment] 2018-03-17 10:39
@malard please just revert the fscking patch.  It'll take seconds and the worst that will happen is LG users won't have to put up with this issue any longer.

**Comment by anomaly256** [comment] 2018-03-17 13:29
It would have taken you as long to revert the broken patch as it did to read and delete that comment.  I understand why you had to delete the comment - but why don't you understand you have to revert commit 9cc4c29?  People have been patient, the problem has been verified, the fix has been verified - why are you stalling?   Is there some specific reason you want a subset of your users to have a constant annoyance?  Do you resent us or something?  Did Sony pay you to give us an inferior experience?  I don't want to believe the reason for this ridiculously long delay is malice, and it's certainly not incompetence, so what is causing the holdup?  What do we do to work around the broken processes and politics at play here?

**Comment by malard** [comment] 2018-03-17 13:31
Hi @anomaly256 i will chase @opdenkamp to update this, but I am the owner of the company and don't know maintain the project personally. Sorry for your frustration

**Comment by anomaly256** [comment] 2018-03-17 13:39
I would greatly appreciate that @malard and I'm sure everyone else here who has commented and +1'd would too as well as the many more who are affected but haven't chimed in on this thread.

I understand you and your devs have priorities but the simple fix for this issue is right there and has been all along.  People have even submitted PRs to address it without reversing the fix the original patch aimed to solve.  It really doesn't make sense why it has persisted so long when the work is already done and just waiting for someone to click one button or another.

**Comment by Vollstrecker** [comment] 2018-03-17 18:11
Interesting, so LG-Users wouldn't have this problem anymore? I am an LG-User, and I would have another problem. It's very similar to https://github.com/Pulse-Eight/libcec/issues/405 with the big difference, that the only way to fix it, is to reboot, while your problem is, that you have to switch channel after you booted. And I'm pretty sure, I'm not the only one out there, maybe just the only one active here.

I don't know why you are constantly rebooting your device, or where the problem of changing a channel after turning the TV on is, but if I want to view a recording while something  else is recorded, I have to wait till recording finishes, or interrupt the recording. Both seems to me more impacting than a channel-switch.

You seem to be able to compile and understand code, so it would be as easy as just commenting out one line to fix it for yourself. An other option, is like the guys at Debian do. If upstream doesn't fix, they just patch it while packaging if they think it the right thing to do, maybe you suggest that to the guys at OSMC (whatever this may be).

And the most interesting part in this story: I had a problem identified it, and solved it (at least for me). It did fix a problem in LGs implementation of CEC, and made another problem whith this visible. 6 month nothing happened and then "someone" came and said "I don't want the problem visible, revert it. The problems of other ones are not mine, and I can't reproduce them".

You took the time to investigate the source of your problems and just say revert it. You could identify what it happening and maybe can find a way which prevents channel-switching after a reconnect happens. I am always open to test other approaches that maybe fix the problems of both of us. I can't reproduce the problem.

If you want, I could give you a patch per day to test if it fixes both problems, but I pretty sure, after the first 3 trys you have no time for more tests.

Push problems to others, just by yelling louder then they do is the absolute wrong way.

**Comment by anomaly256** [comment] 2018-03-17 23:02
@Vollstrecker I think you are slightly mistaken.  It's not when we reboot our devices, it's every single time we turn on our TVs.  Many users report the issue here but very few seem to have reported what you're experiencing - breaking things for many users to solve something for a few doesn't make sense.

Further more, there are PR's waiting that claim to fix this issue without reintroducing your problem.  Why don't you test #390 ?

**Comment by Vollstrecker** [comment] 2018-03-21 21:17
Second part of second chapter of my last answer: "or where the problem of changing a channel after turning the TV on is". I usually use the remote for tunring on my TV, and with this magic device it is possible to change channels, too. Beside the fact, that in 80% of these case I don't view the same channel I was watching when turning it off. I admit, with an external receiver this doesn't apply, but this one could use CEC to switch to the right channel after it is turned on, too.

For the other PR: I didn't notice that one, till you spoke about working solutions. The other one I saw, just changed the order of the if's, which obviously doesn't change anything. I started testing it, right after my last post. I'm pretty sure I tried that variant while writing my initial patch, and it didn't work, while testing this patch, it sometimes works and sometimes not, so I guess I had a situation where it didn't work while writing. I don't see a pattern right now.

**Comment by anomaly256** [comment] 2018-03-21 22:39
@Vollstrecker please stop.  The TV requires several seconds of warm up time before letting me change channels with the remote for some reason, but it'll switch on CEC commands earlier.  It's annoying to start watching something then 5s later switch to hdmi input, then not being able to switch back immediately EVERY SINGLE TIME we turn the tv on.  This is not a situation that should just be accepted because 1 person has an issue with 1 tv somewhere else in the world.  I'm happy your problem got solved but I think it's incredibly selfish that this comes at the cost of many other users' experience and you try to marginalise their situation.

Sometimes works?  At this stage I'd say your tv is just defective.  Have you updated its firmware since you posted the original patch?  Have you updated recently?  It's possible your original problem might not even exist any more in current firmwares.

**Comment by felipesalomao** [comment] 2018-03-22 04:05
Exactly. I use Siri to turn on my tv for example, I have to say turn on tc
the. It start on hdmi 1 (sat), after 6 seconds change alone to kodi
(running on raspberry pi).. Then wait more 4 seconds to say switch to hdmi
1.. Lost sense to use it.. My Sat remote does not command tv, só isso need
keep both remotes with me.. There is no sense..

Em qua, 21 de mar de 2018 às 19:39, Wes <notifications@github.com> escreveu:

**Comment by Stan-Tastic** [comment] 2018-03-22 06:47
I want to confirm that I have the same behavior on Philips TV (which takes like 50-60 seconds to start accepting remote commands). As long as CEC driver is enabled on the Pi, each time I switch on TV first thing it does is to switch to Pi output... then I have to wait for a minute before it will actually accept command to switch back to whatever else (be it console, cable, or aerial).
I disabled CEC completely, because its usefulness is completely destroyed by this bug.

**Comment by stedaniels** [comment] 2018-03-22 09:05
Hiya @Vollstrecker, I have a wife and three kids.  I say hey XYZ, go watch TV whilst I finish up cooking dinner.  Child turns TV on, they're 3 or 4, TV comes on to the last channel it was on (kids TV channel), for a few seconds they are appeased.  After that three of 4 seconds the this daft bug kicks in and switches the TV input from OTA to HDMI1.  Channel buttons now have no affect, they must hunt out the input button which them pulls up this input selection menu, which they must then navigate across to the correct input.  I hope I didn't lose you, because I sure lost my kids, and my wife sure isn't happy.  This is an especially poor user experience.
You're not just making this a poor infuriating experience for one or two people in here, but everyone else who suffers this and get increasingly annoyed at the "Stupid LibreELEC.tv/OSMC/Kodi/Plex/etc./etc.".
Obviously in your opinion, a problem fixed for you is a great thing, and from your point of view it causes no bother.  But for everyone else who've gone through hundreds, thousands of involuntary input changes it is maddening,  If you lack enough empathy to grasp this then I don't think we can discuss this further with you.

There was of course a delay before your patch was released in libcec and people came here to complain, because downstream projects didn't instantly deploy that version of libcec, and then the majority of downstream users have no idea what GitHub is.  As it's filtered through, more and more people have complained in all the downstream forums, a small amount of people have complained on downstream GitHub projects, and an even smaller amount have managed to find them way through to this issue.

I'm pretty sure there has even been a PR that should satisfy both your corner "standards compliant" case and the wider "LG's actual implementation" case that we experience so I have to wonder why you're even arguing your case anymore.  Are you one of those, "I must win the argument" kind of folk?

I'm so lost as the discussion has been had over many forums, PR's and GH issues I have no idea where we are up to.

**Comment by Vollstrecker** [comment] 2018-03-22 09:29
@anomaly256 sometimes works doesn't mean necessary a defective device. I didn't check in the code, but iirc HandleVendorCommandPowerOnStatus checks the active source and if it already is the source, it does nothing. It seems to depend on the active source of the TV when turning off/on, and the time between the 2 events. And no I didn't upgrade the firmware.

From the forum posts you mentioned, I see someone with an LG-TV who doesn't face this problem, and I see someone with a Samsung (which should be affected at all) that has this problem. Another one reports, that he was able to fix this with changed settings. From the same posts it seems to me, that the logs are created within kodi, which runs cec-client side-by-side to itself. Has anyone tried to run cec-client on cmdline without a running kodi?

As I use mythtv, and no reports like that can be found on their bugtracker/forums/gh-repo/whatever, and no reports can be found for distros like mythbuntu, it's possible that kodi does the wrong things.

@stedaniels You're missing twot points about my comparing my corner "standards compliant" device and the wider "LG's actual implementation":

1. My device is still supported, so it has the current interpretation of standard's compliance from LG's POV.

2. Your device has the same implementation of that, as it has to send that bogus signal to trigger the part of code everyone is blaming here.

**Comment by stedaniels** [comment] 2018-03-22 11:24
OK we clearly can't agree that breaking functionality for existing users to work for you and potential others going forward is a bad thing.

How can we move forward?

[On 2 May 2017](https://github.com/Pulse-Eight/libcec/pull/256#issuecomment-298514623) @Vollstrecker wrote:
> The cause for using The PowerON method was just, that I didn't find any other way to get that done.

I obviously can't test any changes that work on my device but don't work on your device, but you can.

Can you add another method copying [CSLCommandHandler::HandleVendorCommandPowerOn](https://github.com/Pulse-Eight/libcec/blob/1a8dc6c96a1c74d2820fea1a39f4dc8057905102/src/libcec/implementations/SLCommandHandler.cpp#L171) call it something like CSLCommandHandler::HandleVendorCommandReconnect strip out the references to changing source such as [device->MarkAsActiveSource();](https://github.com/Pulse-Eight/libcec/blob/1a8dc6c96a1c74d2820fea1a39f4dc8057905102/src/libcec/implementations/SLCommandHandler.cpp#L181) (and others for cleanliness)  and then see if it reconnects by calling HandleVendorCommandReconnect instead of HandleVendorCommandPowerOn on line https://github.com/Pulse-Eight/libcec/blob/1a8dc6c96a1c74d2820fea1a39f4dc8057905102/src/libcec/implementations/SLCommandHandler.cpp#L132

Is this an acceptable way to move forward?

Actually... writing all that, it looks like this commit by @opdenkamp was meant to do this: https://github.com/Pulse-Eight/libcec/commit/1a8dc6c96a1c74d2820fea1a39f4dc8057905102 however it seems to be that https://github.com/Pulse-Eight/libcec/commit/1a8dc6c96a1c74d2820fea1a39f4dc8057905102#diff-5e82a8a73dfb85574a98f4b64dfcb842R190 has the logic inverted it shouldn't be !wasActive  but wasActive.  It'd probably also be good to have the same if logic here wrapped around https://github.com/Pulse-Eight/libcec/commit/1a8dc6c96a1c74d2820fea1a39f4dc8057905102#diff-5e82a8a73dfb85574a98f4b64dfcb842R181.  My c++ us rusty but it might be something I can take a stab at if you don't have time to try either of these methods to see if they work for you.

**Comment by maart84** [comment] 2018-03-22 11:36
To be honest, this bug was annoying me too. I've actually spent lots of hours learning to compile / use docker / use github / creating a patch etc...  just to fix it and for me it was worth it. Libreelec included pull request #390 so this bug is not longer present since 8.2.4. (the bug that sometimes a paused video continued playing might still be there. Therefore I use Millhouse's test builds which fixes both issues for me). I've never compiled OSMC but I might have a look this evening and see if I can create a fix for this

**Comment by stedaniels** [comment] 2018-03-22 11:55
@maart84 thanks for this!  I hadn't noticed, looks like the project I'm interested in (PlexMediaPlayer embedded) is suffering downstream delay.. I'll try and get them to bump up to at least 8.2.4 or add your patch into my own build.  Really appreciate this.

**Comment by Vollstrecker** [comment] 2018-03-22 11:56
> OK we clearly can't agree that breaking functionality for existing users to work for you and potential others going forward is a bad thing.

OK, I don't know what we means, because I can agree that problems should always be solved for all, which includes potentially others on both sides.

> I obviously can't test any changes that work on my device but don't work on your device, but you can.

Sure, but you can test if the reason is really in libCEC and not in kodi like I suggested in my last post.

I'm trying out the changes you mentioned, but don't expect instant results, as the time-ascpect I mentioned is somewhere > 3 hours. And as this behaves different, depending on the state when TV was turned off, I think it will take till tomorrow to get this all together.

Maybe this is enough time to find out if Kodi is causing the problems within their code, I don't like the thought of fixing a wrong implementation of LG, and then add another workaround for third-party software.

And while writing this, when comparing debian and osmc packaging, I just saw, that osmc added patches that influence source-activation aswell, and this is living in the repo longer than their upgrade to v4, so we maybe have another option of who broke this.

**Comment by Vollstrecker** [comment] 2018-03-22 12:03
And I forgot: Did you try if the patch you mentioned fixes this for you, too? With or without the !

From the first thought this ! is really missplaced.

**Comment by ghus-raba** [comment] 2018-03-23 09:13
This is happenning for me on a Phillips TV, and above are mentions of at least Samsung as well, so it does not seem like there is one wrong implementation on LG affecting minimum users.

@maart84 I am running Libreelec 8.2.4 and I still see this happen. Are you sure it should be fixed in that version?

**Comment by maart84** [comment] 2018-03-23 11:51
Oops, I'm sorry for the confusion, but it seems the patch is not included in the 2.8.4 build. It is in the master branch. [Here ](https://forum.libreelec.tv/thread/10031-lg-tv-switching-input-8-1-x/?pageNo=2) is an older 8.2.0.1 that should include the fix. I'll have a look if i can build a 2.8.4 with the fix this weekend.

**Comment by mfarrell34** [comment] 2018-03-23 14:33
@Vollstrecker this almost certainly isn't a kodi issue. I reproduced it about a year ago with a raspberry pi using libcec connected directly to an LG tv without kodi involved. The tv just has SIMPLINK enabled, LG's implementation of CEC. After deleting the changes made in PR #256 and recompiling libcec the issue stopped occurring.

I agree that fixing it for everyone is ideal, unfortunately LG's implementation of CEC doesn't seem to be standard. I had reached out to LG's support about a year ago to try and get more information about the commands used in SIMPLINK. Unsurprisingly though once I was able to find someone from their support that actually knew what CEC was I never got another response from them, and I'd forgotten about this issue since then. Now that some patches seem to be available I should have time this weekend to try them out and generate some new logs, I can't seem to find the log files from when I originally reproduced it.

**Comment by maart84** [comment] 2018-03-24 10:55
Here's a link with my build for Libreelec 8.2.4 which includes the latest libcec and the fix for this issue. 
https://maart84.stackstorage.com/s/5g6Am7wbiSqtnD1

**Comment by anomaly256** [comment] 2018-03-25 01:40
I can confirm #390 fixes the issue for me.  @Vollstrecker does your problem remain fixed when you apply #390 or not?  Your response wasn't very clear to me.

And I'd strongly suggest upgrading your firmware since you said you haven't yet.  There is every possibility your problem doesn't even exist any more (but of course it might still exist).  Breaking libcec for many users to address a problem that doesn't even exist in current firmwares would be even more silly than the current situation

**Closed** 2020-10-26 08:25 UTC
Labels: bug, next major release
